Lab5/lab5/exchangeRate/urls.py
from django.urls import path

from . import views

app_name = 'exchangeRate'
urlpatterns = [
    path('', views.Main.as_view(), name='main'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

Lab5/lab5/lab5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('exchangeRate/', include('exchangeRate.urls')),
    path('admin/', admin.site.urls),
]

Lab5/lab5/exchangeRate/models.py
import django.db.models
from django.db import models

import pandas


class Currency(models.Model):
    charCode = models.CharField(max_length=3)
    name = models.CharField(max_length=100)
    value = models.FloatField()

    @staticmethod
    def create_data():
        url = "http://www.cbr.ru/scripts/XML_daily.asp"

        df = pandas.read_xml(url, encoding='cp1251')

        for i in range(len(df['Value'])):
            df['Value'][i] = str(df['Value'][i]).replace(',', '.')

        model_instances = [Currency(
            charCode=df.iloc[i]['CharCode'],
            name=df.iloc[i]['Name'],
            value=float(df.iloc[i]['Value'])
        ) for i in range(len(df))]

        Currency.objects.bulk_create(model_instances)

Lab5/lab5/exchangeRate/views.py
from django.shortcuts import render
from django.views import generic
from .models import Currency


class Main(generic.ListView):
    template_name = 'exchangeRate/main.html'
    context_object_name = 'currency_list'

    def get_queryset(self):
        return Currency.objects.all()


class DetailView(generic.DetailView):
    model = Currency
    template_name = 'exchangeRate/detail.html'

Lab5/lab5/exchangeRate/templates/exchangeRate/detail.html
{% load static %}

<link rel="stylesheet" href="{% static 'exchangeRate/style.css' %}">
<h1 align="center">{{ currency.name }}</h1>
<h2 align="center">{{ currency.value }}</h2>

Lab5/lab5/exchangeRate/templates/exchangeRate/main.html
{% load static %}

<link rel="stylesheet" href="{% static 'exchangeRate/style.css' %}">
{% if currency_list %}
    <h1>Список валют</h1> <h3>(нажмите на валюте, чтобы посмотреть её котировку)</h3>
    <ul>
    {% for currency in currency_list %}
        <li><a href="{% url 'exchangeRate:detail' currency.id %}">{{ currency.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Error: Look for your data!!!.</p>
{% endif %}